### ISSUE TITLE
How do I actually install this?

### ISSUE THREAD

**Issue by jahndae17** [Kryeit/Telepost-Refabricated#3]
I like the sound of this mod, but I am struggling with the setup

_"How to use /buildpost: place in `world/generated/structures/minecraft` a `default.nbt`, then place any other .nbt with a biome name, such as `plains.nbt`. Posts will be built with that structure depending on the biome, if none found, the default will be used."_

This is confusing...

- What is actually meant to be in the file `default.nbt`? I only get the jar file when I download this mod from modrinth; so where am I meant to be finding this default file?
    - My best guess is the files in `src/main/resources/structures`, but then I don't understand where to put this file.
![image](https://github.com/Kryeit/Telepost/assets/68041585/f67fd15a-369e-4897-b642-1399776f54e4)
- This directory given to place the _"default.nbt"_ file (`world/generated/structures/minecraft`) does not exist? If I go into `.minecraft/saves/new_world`... then I get this
![image](https://github.com/Kryeit/Telepost/assets/68041585/a2c84881-da3b-4043-9251-ed56ec9ebffc)

If I just load up the mod without doing anything else, then none of the commands work properly\
![image](https://github.com/Kryeit/Telepost/assets/68041585/0fbb1381-d8f8-43d5-b8c5-8f9fa2cce6de)

I believe I have installed all the dependencies (including "luckperms", and "fabric api" which are only listed as a dependency under `src/main/resources` on github, but shouldn't be required per modrinth). Vanilla permissions are on via lan, as the gamemode command demonstrates.
![image](https://github.com/Kryeit/Telepost/assets/68041585/cba97e14-8877-4d96-ac53-4b29e3da0e28)
![image](https://github.com/Kryeit/Telepost/assets/68041585/e156dbcd-1da3-4f9e-8e09-4ca3a2f81b5a)
![image](https://github.com/Kryeit/Telepost/assets/68041585/b66075cf-11a6-48ae-97bd-09cbd1d86d23)
![image](https://github.com/Kryeit/Telepost/assets/68041585/52cfbced-090c-4296-af1b-6919cde91dbb)
![image](https://github.com/Kryeit/Telepost/assets/68041585/cb91d79a-179d-48d0-bb2d-4136d5f8ded5)

**Summary?**
Is there some kind of terms and conditions I am not accepting?
Am I meant to create the directory?
Is there a place that explains the install process in more detail?

**Comment by jahndae17** [comment]
(I saw [Prometheus](https://modrinth.com/mod/prometheus) mentioned somewhere or another... So my other theory is this is actually only for servers?)

**Comment by MrRedRhino** [comment]
The mod is made for servers but should work in singleplayer too. You might have to give your self permission through LuckPerms to use the commands. I don't know where you read about prometheus, but it's not used in this mod

**Comment by muriplz** [comment]
> I like the sound of this mod, but I am struggling with the setup
> 
> _"How to use /buildpost: place in `world/generated/structures/minecraft` a `default.nbt`, then place any other .nbt with a biome name, such as `plains.nbt`. Posts will be built with that structure depending on the biome, if none found, the default will be used."_
> 
> This is confusing...
> 
> * What is actually meant to be in the file `default.nbt`? I only get the jar file when I download this mod from modrinth; so where am I meant to be finding this default file?
>   
>   * My best guess is the files in `src/main/resources/structures`, but then I don't understand where to put this file.
>     ![image](https://private-user-images.githubusercontent.com/68041585/320468425-f67fd15a-369e-4897-b642-1399776f54e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0Njg0MjUtZjY3ZmQxNWEtMzY5ZS00ODk3LWI2NDItMTM5OTc3NmY1NGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MGIyOTIwNmViOThlZDRlNWMwZmY0NjAzZmQ3YzA5Yjk2OWIzMmU1ODVjYzYyYmM5NGFjNWViNTQyNDliMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8TuA96KPmHn_F1oLGUnhYIdTLWZvpg0D0KmMAy5t7tU)
> * This directory given to place the _"default.nbt"_ file (`world/generated/structures/minecraft`) does not exist? If I go into `.minecraft/saves/new_world`... then I get this
>   ![image](https://private-user-images.githubusercontent.com/68041585/320466596-a2c84881-da3b-4043-9251-ed56ec9ebffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0NjY1OTYtYTJjODQ4ODEtZGEzYi00MDQzLTkyNTEtZWQ1NmVjOWViZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYWVkM2YzOTkwMzAwNDQ3MDk2MmNkODhlNzcwNTE0MTk0Y2U4MDZhNzhiOTAzNWM5MWFjMmU5NjAxNWVhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vAYh-egLyOeWcVYm_RK22te2V17mVDoKmHwNK-WkzEQ)
> 
> If I just load up the mod without doing anything else, then none of the commands work properly ![image](https://private-user-images.githubusercontent.com/68041585/320474246-0fbb1381-d8f8-43d5-b8c5-8f9fa2cce6de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0NzQyNDYtMGZiYjEzODEtZDhmOC00M2Q1LWI4YzUtOGY5ZmEyY2NlNmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYzI5MzU2NDA0MmRkYjYxNGE2NzA5OTg4Y2RjYTk4YTMyYWJmOTQwNjRmODhmMDE5N2RkMWY1OTllOWUyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.znNmPULdWbhNO3zMAWPszSD4uxrbzM-KNdjxkVOCu0A)
> 
> I believe I have installed all the dependencies (including "luckperms", and "fabric api" which are only listed as a dependency under `src/main/resources` on github, but shouldn't be required per modrinth). Vanilla permissions are on via lan, as the gamemode command demonstrates. ![image](https://private-user-images.githubusercontent.com/68041585/320474981-cba97e14-8877-4d96-ac53-4b29e3da0e28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0NzQ5ODEtY2JhOTdlMTQtODg3Ny00ZDk2LWFjNTMtNGIyOWUzZGEwZTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OTZiOTM2ZTkxMjllOGU2ZGU4YjcxOTJmOTU5ODE2NGMyMTFjOWRkNjFiNTNlMThjODgxNjgzZGNkOGRiZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2KBypVU-iOYipQKHG6yOFJ_RgRd6uZZPxPjfXZ5bXJI) ![image](https://private-user-images.githubusercontent.com/68041585/320475547-e156dbcd-1da3-4f9e-8e09-4ca3a2f81b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0NzU1NDctZTE1NmRiY2QtMWRhMy00ZjllLThlMDktNGNhM2EyZjgxYjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjE3ODZlMzU1Yzg1MWQzMGQ5ZTQ2ZDNjZmRlYTdjYjE5MzJkZjk5ZTEzNDIzYWZlYWJjM2Y3OTNlNjgxOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gCmI06grs10Jk53qkOcZIKUIq7WL7Wl-nGWMsMB_eLw) ![image](https://private-user-images.githubusercontent.com/68041585/320471717-b66075cf-11a6-48ae-97bd-09cbd1d86d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0NzE3MTctYjY2MDc1Y2YtMTFhNi00OGFlLTk3YmQtMDljYmQxZDg2ZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmM2Y5NDM5OWUwOGNkYmZmYjc2OWIwZWVjYmVmOGEzZWUxNTU4ODg0NjYxNDRkNjJhYjY4NDU3YzYzZTY4Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eXybS5cGr8sssCpVEiFaEIKPCerk_O74J9OIPQiYDmk) ![image](https://private-user-images.githubusercontent.com/68041585/320471843-52cfbced-090c-4296-af1b-6919cde91dbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0NzE4NDMtNTJjZmJjZWQtMDkwYy00Mjk2LWFmMWItNjkxOWNkZTkxZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDE3NzA0MGM2ZDBkMTZjZmNlODk4NmUzMjA2NWFhYzYxZmQ5YjYyZDFmZmZkZDMzN2I4ZDhjNWRjZGRiNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2J7fGBkDdU9b3LDylFGn0P581mgGciT3zp6G4xS8kMI) ![image](https://private-user-images.githubusercontent.com/68041585/320469376-cb91d79a-179d-48d0-bb2d-4136d5f8ded5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzMyODgsIm5iZiI6MTcxMjczMjk4OCwicGF0aCI6Ii82ODA0MTU4NS8zMjA0NjkzNzYtY2I5MWQ3OWEtMTc5ZC00OGQwLWJiMmQtNDEzNmQ1ZjhkZWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTk0MmMxMWQ0NWQxODUzNWJhYzJjMzdmMDg1NjM0ZTIzNjQ1NzY1N2Q3MGFmZmI2OTc2Mzk4NWVmNDdmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p2wvIqR7ncl0obUZim8-DmOvN4xQ_6cq7ZQly1xFu3I)
> 
> **Summary?** Is there some kind of terms and conditions I am not accepting? Am I meant to create the directory? Is there a place that explains the install process in more detail?
1) Where are the structures .nbt's?
They are where the structures should be saved, at: `world/generated/structures/minecraft/`
2) You are using an outdated build, where you needed to create the folders manually in order for them to appear. I've updated the build in modrinth which also comes with many fixes

**Comment by muriplz** [comment]
and yeah, I'll ffix that luckperms softdepend, sorry

**Comment by muriplz** [comment]
Prometheus was mentioned to bring compat to /back with Telepost, so it updates when teleporting to a post
